window.DEER_VALLEY_MANUAL_REVIEWS = [
  {
    id: 'airbnb-rafael-2026-02',
    platform: 'airbnb',
    guestName: 'Rafael',
    location: 'San Diego, California',
    dateText: 'February 2026 · Stayed a few nights',
    rating: 5,
    text: "One of the best Airbnbs we've ever stayed at. Stunning mountain views, cozy design, and amenities you don't expect at this price. Vivian thought of everything. Don't hesitate, just book it!",
    featured: true,
    featuredRank: 1,
  },
  {
    id: 'airbnb-nicholas-2026-03',
    platform: 'airbnb',
    guestName: 'Nicholas',
    location: 'Tampa, Florida',
    dateText: '1 week ago · Stayed a few nights',
    rating: 5,
    text: "Vivian is an incredible host. Her place looked just like the listing and she had some great recommendations on local things to do. The check in was seamless and I appreciated the cleanliness and decor when I arrived. For a family ski trip, I couldn't recommend a better place. The drive to the slopes was easy and it was so nice to come back and sit in the jacuzzi with my kids. I will definitely be back!",
    featured: true,
    featuredRank: 2,
  },
  {
    id: 'airbnb-tina-2026-03',
    platform: 'airbnb',
    guestName: 'Tina',
    location: 'Salt Lake City, Utah',
    dateText: '2 weeks ago · Stayed with kids',
    rating: 5,
    text: 'We enjoyed our time at the deer valley base camp. House is new and cleaned. Very inviting atmosphere. We enjoyed the hot tub and the kids entertainment. Will stay again for sure.',
    featured: false,
    featuredRank: 3,
  },
];
